<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <!-- Ensure nuget.org is available as a restore source when running restore in constrained environments -->
    <RestoreSources>https://api.nuget.org/v3/index.json;$(RestoreSources)</RestoreSources>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AppDesignerFolder>Config</AppDesignerFolder>
  </PropertyGroup>
  <ItemGroup>
    <None Update="res\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>


</Project>
